"use strict";

module.exports = {
  SERVER_ADDRESS:   'http://localhost:3000',
  PROJECT_NAME:     'MilkTools',
  HOME:             'Principal',
  CATTLE:           'Rebanho',
  INPUT:            'Insumos',
  PRODUCTION:       'Produção',
  CATTLE_LIST:      'Lista',
  CATTLE_REGISTER:  'Adicionar',
  PRINCIPAL_HEADER: 'Métricas',
  USER:             'Usuário',
  PASSWORD:         'Senha',
  LOGIN:            'Entrar',
  REGISTER_CATTLE:  'Cadastrar Animal',
  NAME:             'Nome',
  GENDER:            'Gênero',
  COAT:             'Pelagem',
  RGD:              'RGD',
  FATHER:           'Pai',
  BREED:            'Raça',
  Earring_Number:   'Número do brinco',
  SOURCE:           'Origem',
  BIRTHDAY:         'Data de Nascimento',
  RGN:              'RGN',
  MOTHER:           'Mãe',
  COMMENTS:         'Observações',
  SAVE:             'Salvar',
  CHOOSE_ONE:       'Selecione um ...',
  BIRTH:            'Nascimento',
  BUY:              'Compra',
  HOLANDESA:        'Holandesa',
  JERSEY:           'Jersey',
  PARDO_SUICA:      'Pardo Suíça',
  GIROLANDO:        'Girolando',
  GIR_LEITEIRO:     'Gir Leiteiro',
  PINZGUAER:        'Pinzguaer',
  SIMENTAL:         'Simental',
  RED_POLLED:       'Red Polled',
  CARACU:           'Caracu',
  PITANGUEIRAS:     'Pitangueiras',
  NORMANDO:         'Normando',
  GUERNSEY:         'Guernsey',
  AYRSHIRE:         'Ayrshire',
  MALE:             'Macho',
  FEMALE:           'Fêmea',
  LIST_CATTLE:      'Listar Rebanho',
  DETAIL_CATTLE:    'Detalhar Animal',
  STATUS:           'Estado',
  EDIT:             'Editar',
  REGISTER_PRODUCTION: 'Adicionar Produção',
  DAILY_PRODUCTION: 'Litros de Leite',
  LIST_PRODUCTION: 'Produção Diária',

  MSG_USER_INAVLID: 'Usuário e/ou senha inválidos!',
  MSG_ERROR_SAVE_CATTLE: "Erro ao salvar as informações: ",
  MSG_SUCCESS_SAVE_CATTLE: "As informações foram salvas com sucesso!",
  MSG_SUCCESS_REMOVED_CATTLE: "O animal foi removido com sucesso!",
  MSG_ERROR_NOT_NUMBER: "Valor informado é inválido, deve ser um número.",
  MSG_ERROR_PRODUCTION_NOT_FILLED: "A produção diária deve ser preenchida.",
  MSG_ERROR_NUMBER_MORE_THAN_ZERO: "O número informado dever ser maior que zero",
  MSG_SUCCESS_SAVE_PRODUCTION: "A produção do dia foi salva com sucesso.",
  MSG_ERROR_SAVE_PRODUCTION: "Erro ao salvar a produção:",
  MSG_SUCCESS_REMOVED_PRODUCTION: "A produção foi removida com sucesso."
};
