'use strict';
// router.js
// Attach the routes to the App
const index    = require('./routes/index');
const users    = require('./routes/users.router');
const cattle   = require('./routes/cattle.router')
const production   = require('./routes/production.router')

/**
 * This method configure the routes subpaths to the application
 * @method function
 * @param  {express()} app The app generated by calling the express() function
 * @return {void}
 */
const route = function(app) {
  // configure the routes
  app.use('/', index);
  app.use('/users', users(app));
  app.use('/cattle', cattle(app));
  app.use('/production', production(app));
};

module.exports = {
  configure: route
};
