/*
** Consulta que retorna os carros e os modelos
*/
select v.PLACAATUALVEIC,v.CAPACIDADETANQUEVEIC,v.PREFIXOVEIC,mc.DESCRICAOMODCARROC,fc.DESCRICAOMARCARROC,mch.DESCRICAOMODCHASSI,fch.DESCRICAOMARCHASSI from FRT_CADVEICULOS v 
  JOIN FRT_MODCARROC mc ON mc.CODIGOMODCARROC = v.CODIGOMODCARROC 
  JOIN FRT_MARCACARROC fc on fc.CODIGOMARCARROC = mc.CODIGOMARCARROC
  JOIN FRT_MODCHASSI mch on mch.CODIGOMODCHASSI = v.CODIGOMODCHASSI
  JOIN FRT_MARCACHASSI fch on mch.CODIGOMARCHASSI = fch.CODIGOMARCHASSI;
  
