// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

funcionarios = [
  "Gustavo Daniel Soares Figueiredo",
  "MAURICIO RAPHAEL WAISBLUM BARG"
]

const waitNormal = 3000
const waitLong = 6000
for(i=0; i < funcionarios.length; i++){
    const funcionario = funcionarios[i]
    describe('aprovar_geral', function() {
      this.timeout(80000)
      let driver
      let vars
      beforeEach(async function() {
        driver = await new Builder().forBrowser('firefox').build()
        vars = {}
      })
      afterEach(async function() {
        await driver.quit();
      })
      it('aprovar_geral', async function() {
        await driver.get("https://www.mdcomune.com.br/Madis/Account/LogOn?timeOutLoginComo=False")
        await driver.manage().window().setRect(1207, 800)
        await driver.findElement(By.id("LogOnModel_UserName")).click()
        await driver.findElement(By.id("LogOnModel_UserName")).sendKeys("flavio.junior@radixeng.com.br")
        await driver.findElement(By.id("LogOnModel_Password")).sendKeys("12345")
        await driver.findElement(By.id("LogOnModel_Password")).sendKeys(Key.ENTER)
        await driver.sleep(waitLong);
        await driver.findElement(By.css(".fgmujM")).click()
        await driver.sleep(waitLong);
        await driver.findElement(By.css(".sc-bdVaJa")).click()
        await driver.sleep(waitNormal);
        await driver.findElement(By.css(".pendingRequestsIcon")).click()
        await driver.sleep(waitNormal);
        await driver.findElement(By.id("Tab1")).click()
        await driver.sleep(waitNormal);
        await driver.findElement(By.id("filterResumeMessagesButton")).click()
        await driver.sleep(waitNormal);
        await driver.findElement(By.id("userAutocomplete")).sendKeys(funcionario)
        await driver.sleep(waitNormal);
        await driver.findElement(By.id("SearchButtonPessoa")).click()
        await driver.sleep(waitLong);
        await driver.findElement(By.css(".checkboxCustom")).click()
        await driver.sleep(waitNormal);
        await driver.findElement(By.id("aprovarTodos")).click()
        await driver.sleep(waitNormal);
        await driver.findElement(By.xpath("//span[@id='baprovarTodos']")).click()
        await driver.sleep(waitLong);
        //await driver.executeScript("return alert(123)")
        await driver.close()
      })
    });
}