'use strict';
// router.js
// Attach the routes to the App
const index    = require('./routes/index');
const users    = require('./routes/users.router');
const workload = require('./routes/workload.router');
const model    = require('./routes/model.router');

/**
 * This method configure the routes subpaths to the application
 * @method function
 * @param  {express()} app The app generated by calling the express() function
 * @return {void}
 */
const route = function(app) {
  // configure the routes
  app.use('/', index);
  app.use('/workloads', workload(app));
  app.use('/users', users(app));
  app.use('/model', model(app));
};

module.exports = {
  configure: route
};
